[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
	symlink://..
build_flags =
	-D ARDUINO_LOOP_STACK_SIZE=16384
	; -D FCM_DECRYPT_VIA_SERVER=1

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.f_cpu = 160000000L
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
	symlink://..
build_flags =
	-D FCM_REQUIRE_PREGENERATED_CREDENTIALS=1
	-D FCM_DECRYPT_VIA_SERVER=1
